<a href="https://colab.research.google.com/github/Vidya95-t/Google-playstore-apps-extended/blob/main/PROJECT_1_GOOGLE_PLAY_STORE_APPS_EXTENDED_sample.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# GOOGLE PLAYSTORE APPS EXTENDED

### Although Google Play acts as a digital media store as well, the data covers only mobile applications.

### The Play Store apps data has enormous potential todrive app-making businesses to success.
### Actionableinsights can be drawn for developers to work on andcapture the Android market.
### The app market isgrowing with a dynamic speed and is ever changing.

### The Google Play Store is the largest and most popular Android app store.

### We collected descriptive information on over 3,100 apps across 11 different categories in the Google App Store.
### We focused on the following 11 categories: Business, Food & Drink, Books & Reference, Travel & Local, Health & Fitness,News & Magazines, Education, Social, Finance, Medical, and Entertainment.

### Each app has its own web page where detailed information about the app is available.
### We used Selenium to scrape information about each of these apps for our analysis.
### We scraped app title, category, developer name, whether an app contains ads, rating, number of reviews,app size, number of installs, and price.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#importing pandas library
import pandas as pd
#importing numoy library
import numpy as np

In [ ]:
#importing csv file extended_googleplaystore

df = pd.read_csv("extended_googleplaystore.csv")
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,...,Last Updated (Year),Last Updated (Year/Month),Category (categorical),Type (categorical),Genres (categorical),Current Ver (categorical),Android Ver (categorical),Last Updated (Year/Month) (categorical),No_reviews_count,Reviews_present_count
0,Photo Editor & Candy Camera & Grid & ScrapBook,0.0,4.1,159,19.0,10000.0,0.0,0.0,Everyone,9.0,...,2018,80.0,ART_AND_DESIGN,Free,Art & Design,1.0.0,4.0.3 and up,2018-01,0,0
1,Coloring book moana,0.0,3.9,967,14.0,500000.0,0.0,0.0,Everyone,12.0,...,2018,80.0,ART_AND_DESIGN,Free,Art & Design;Pretend Play,2.0.0,4.0.3 and up,2018-01,14,44
2,"U Launcher Lite â€“ FREE Live Cool Themes, Hide ...",0.0,4.7,87510,8.7,5000000.0,0.0,0.0,Everyone,9.0,...,2018,87.0,ART_AND_DESIGN,Free,Art & Design,1.2.4,4.0.3 and up,2018-08,0,0
3,Sketch - Draw & Paint,0.0,4.5,215644,25.0,50000000.0,0.0,0.0,Teen,9.0,...,2018,85.0,ART_AND_DESIGN,Free,Art & Design,Varies with device,4.2 and up,2018-06,0,0
4,Pixel Draw - Number Art Coloring Book,0.0,4.3,967,2.8,100000.0,0.0,0.0,Everyone,11.0,...,2018,85.0,ART_AND_DESIGN,Free,Art & Design;Creativity,1.1,4.4 and up,2018-06,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9654,Sya9a Maroc - FR,11.0,4.5,38,53.0,5000.0,0.0,0.0,Everyone,38.0,...,2017,74.0,FAMILY,Free,Education,1.48,4.1 and up,2017-07,0,0
9655,Fr. Mike Schmitz Audio Teachings,11.0,5.0,4,3.6,100.0,0.0,0.0,Everyone,38.0,...,2018,86.0,FAMILY,Free,Education,1.0,4.1 and up,2018-07,0,0
9656,Parkinson Exercices FR,20.0,NaN,3,9.5,1000.0,0.0,0.0,Everyone,70.0,...,2017,68.0,MEDICAL,Free,Medical,1.0,2.2 and up,2017-01,0,0
9657,The SCP Foundation DB fr nn5n,3.0,4.5,114,NaN,1000.0,0.0,0.0,Mature 17+,19.0,...,2015,44.0,BOOKS_AND_REFERENCE,Free,Books & Reference,Varies with device,Varies with device,2015-01,0,0
9658,iHoroscope - 2018 Daily Horoscope & Astrology,18.0,4.5,398307,19.0,10000000.0,0.0,0.0,Everyone,66.0,...,2018,86.0,LIFESTYLE,Free,Lifestyle,Varies with device,Varies with device,2018-07,0,0

In [ ]:
#previewing first 5 rows of the data

df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,...,Last Updated (Year),Last Updated (Year/Month),Category (categorical),Type (categorical),Genres (categorical),Current Ver (categorical),Android Ver (categorical),Last Updated (Year/Month) (categorical),No_reviews_count,Reviews_present_count
0,Photo Editor & Candy Camera & Grid & ScrapBook,0.0,4.1,159,19.0,10000.0,0.0,0.0,Everyone,9.0,...,2018,80.0,ART_AND_DESIGN,Free,Art & Design,1.0.0,4.0.3 and up,2018-01,0,0
1,Coloring book moana,0.0,3.9,967,14.0,500000.0,0.0,0.0,Everyone,12.0,...,2018,80.0,ART_AND_DESIGN,Free,Art & Design;Pretend Play,2.0.0,4.0.3 and up,2018-01,14,44
2,"U Launcher Lite â€“ FREE Live Cool Themes, Hide ...",0.0,4.7,87510,8.7,5000000.0,0.0,0.0,Everyone,9.0,...,2018,87.0,ART_AND_DESIGN,Free,Art & Design,1.2.4,4.0.3 and up,2018-08,0,0
3,Sketch - Draw & Paint,0.0,4.5,215644,25.0,50000000.0,0.0,0.0,Teen,9.0,...,2018,85.0,ART_AND_DESIGN,Free,Art & Design,Varies with device,4.2 and up,2018-06,0,0
4,Pixel Draw - Number Art Coloring Book,0.0,4.3,967,2.8,100000.0,0.0,0.0,Everyone,11.0,...,2018,85.0,ART_AND_DESIGN,Free,Art & Design;Creativity,1.1,4.4 and up,2018-06,0,0

In [ ]:
#viewing last 5 rows of the data

df.tail()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,...,Last Updated (Year),Last Updated (Year/Month),Category (categorical),Type (categorical),Genres (categorical),Current Ver (categorical),Android Ver (categorical),Last Updated (Year/Month) (categorical),No_reviews_count,Reviews_present_count
9654,Sya9a Maroc - FR,11.0,4.5,38,53.0,5000.0,0.0,0.0,Everyone,38.0,...,2017,74.0,FAMILY,Free,Education,1.48,4.1 and up,2017-07,0,0
9655,Fr. Mike Schmitz Audio Teachings,11.0,5.0,4,3.6,100.0,0.0,0.0,Everyone,38.0,...,2018,86.0,FAMILY,Free,Education,1.0,4.1 and up,2018-07,0,0
9656,Parkinson Exercices FR,20.0,NaN,3,9.5,1000.0,0.0,0.0,Everyone,70.0,...,2017,68.0,MEDICAL,Free,Medical,1.0,2.2 and up,2017-01,0,0
9657,The SCP Foundation DB fr nn5n,3.0,4.5,114,NaN,1000.0,0.0,0.0,Mature 17+,19.0,...,2015,44.0,BOOKS_AND_REFERENCE,Free,Books & Reference,Varies with device,Varies with device,2015-01,0,0
9658,iHoroscope - 2018 Daily Horoscope & Astrology,18.0,4.5,398307,19.0,10000000.0,0.0,0.0,Everyone,66.0,...,2018,86.0,LIFESTYLE,Free,Lifestyle,Varies with device,Varies with device,2018-07,0,0

In [ ]:
#checking the shape of the data

numberofrows_1, numberofcolumns_1 = df.shape
print('There are {} rows and {} columns'.format(numberofrows_1, numberofcolumns_1)+' in our Dataset.')

There are 9659 rows and 23 columns in our Dataset.

In [ ]:
#Information about the datatypes and columns

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9659 entries, 0 to 9658
Data columns (total 23 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   App                                      9659 non-null   object
 1   Category                                 9659 non-null   float64
 2   Rating                                   8196 non-null   float64
 3   Reviews                                  9659 non-null   int64
 4   Size                                     8432 non-null   float64
 5   Installs                                 9659 non-null   float64
 6   Type                                     9659 non-null   float64
 7   Price                                    9659 non-null   float64
 8   Content Rating                           9659 non-null   object
 9   Genres                                   9659 non-null   float64
 10  Last Updated                             9659 non-null   object
 11  Current Ver                              9659 non-null   float64
 12  Android Ver                              9659 non-null   float64
 13  Last Updated (Year)                      9659 non-null   int64
 14  Last Updated (Year/Month)                9659 non-null   float64
 15  Category (categorical)                   9659 non-null   object
 16  Type (categorical)                       9658 non-null   object
 17  Genres (categorical)                     9659 non-null   object
 18  Current Ver (categorical)                9651 non-null   object
 19  Android Ver (categorical)                9657 non-null   object
 20  Last Updated (Year/Month) (categorical)  9659 non-null   object
 21  No_reviews_count                         9659 non-null   int64
 22  Reviews_present_count                    9659 non-null   int64
dtypes: float64(10), int64(4), object(9)
memory usage: 1.7+ MB

In [ ]:
#Generating descriptive statistics for overview

df.describe()

,Category,Rating,Reviews,Size,Installs,Type,Price,Genres,Current Ver,Android Ver,Last Updated (Year),Last Updated (Year/Month),No_reviews_count,Reviews_present_count
count,9659.000000,8196.000000,9.659000e+03,8432.000000,9.659000e+03,9659.000000,9659.000000,9659.000000,9659.000000,9659.000000,9659.000000,9659.000000,9659.000000,9659.000000
mean,16.760120,4.173243,2.165926e+05,20.395289,7.777507e+06,0.078165,1.099299,63.777720,1204.159954,16.945232,2017.345688,77.520551,2.653173,3.719743
std,8.400732,0.536625,1.831320e+06,21.827542,5.375828e+07,0.268831,16.852152,32.352326,925.247113,6.966001,1.137600,13.329407,12.469487,16.463267
min,0.000000,1.000000,0.000000e+00,0.008500,0.000000e+00,-1.000000,0.000000,0.000000,-1.000000,-1.000000,2010.000000,0.000000,0.000000,0.000000
25%,11.000000,4.000000,2.500000e+01,4.600000,1.000000e+03,0.000000,0.000000,38.000000,317.500000,13.000000,2017.000000,75.000000,0.000000,0.000000
50%,14.000000,4.300000,9.670000e+02,12.000000,1.000000e+05,0.000000,0.000000,66.000000,1015.000000,17.000000,2018.000000,84.000000,0.000000,0.000000
75%,25.000000,4.500000,2.940100e+04,28.000000,1.000000e+06,0.000000,0.000000,95.000000,1984.000000,20.000000,2018.000000,86.000000,0.000000,0.000000
max,32.000000,5.000000,7.815831e+07,100.000000,1.000000e+09,1.000000,400.000000,117.000000,2816.000000,32.000000,2018.000000,87.000000,240.000000,312.000000

In [ ]:
#Listing all the column names in the dataset

df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver', 'Last Updated (Year)', 'Last Updated (Year/Month)',
       'Category (categorical)', 'Type (categorical)', 'Genres (categorical)',
       'Current Ver (categorical)', 'Android Ver (categorical)',
       'Last Updated (Year/Month) (categorical)', 'No_reviews_count',
       'Reviews_present_count'],
      dtype='object')

In [ ]:
#visualizing the null values in the dataset

df.isnull()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,...,Last Updated (Year),Last Updated (Year/Month),Category (categorical),Type (categorical),Genres (categorical),Current Ver (categorical),Android Ver (categorical),Last Updated (Year/Month) (categorical),No_reviews_count,Reviews_present_count
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9654,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9655,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9656,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9657,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9658,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
#Finding the number of null values in each column

df.isnull().sum()

App                                           0
Category                                      0
Rating                                     1463
Reviews                                       0
Size                                       1227
Installs                                      0
Type                                          0
Price                                         0
Content Rating                                0
Genres                                        0
Last Updated                                  0
Current Ver                                   0
Android Ver                                   0
Last Updated (Year)                           0
Last Updated (Year/Month)                     0
Category (categorical)                        0
Type (categorical)                            1
Genres (categorical)                          0
Current Ver (categorical)                     8
Android Ver (categorical)                     2
Last Updated (Year/Month) (categorical)       0
No_reviews_count                              0
Reviews_present_count                         0
dtype: int64

In [ ]:
df.describe(include="all")

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,...,Last Updated (Year),Last Updated (Year/Month),Category (categorical),Type (categorical),Genres (categorical),Current Ver (categorical),Android Ver (categorical),Last Updated (Year/Month) (categorical),No_reviews_count,Reviews_present_count
count,9659,9659.000000,8196.000000,9.659000e+03,8432.000000,9.659000e+03,9659.000000,9659.000000,9659,9659.000000,...,9659.000000,9659.000000,9659,9658,9659,9651,9657,9659,9659.000000,9659.000000
unique,9659,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,...,NaN,NaN,33,2,118,2817,33,88,NaN,NaN
top,Photo Editor & Candy Camera & Grid & ScrapBook,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Everyone,NaN,...,NaN,NaN,FAMILY,Free,Tools,Varies with device,4.1 and up,2018-07,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7903,NaN,...,NaN,NaN,1832,8902,826,1055,2202,2320,NaN,NaN
mean,NaN,16.760120,4.173243,2.165926e+05,20.395289,7.777507e+06,0.078165,1.099299,NaN,63.777720,...,2017.345688,77.520551,NaN,NaN,NaN,NaN,NaN,NaN,2.653173,3.719743
std,NaN,8.400732,0.536625,1.831320e+06,21.827542,5.375828e+07,0.268831,16.852152,NaN,32.352326,...,1.137600,13.329407,NaN,NaN,NaN,NaN,NaN,NaN,12.469487,16.463267
min,NaN,0.000000,1.000000,0.000000e+00,0.008500,0.000000e+00,-1.000000,0.000000,NaN,0.000000,...,2010.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000
25%,NaN,11.000000,4.000000,2.500000e+01,4.600000,1.000000e+03,0.000000,0.000000,NaN,38.000000,...,2017.000000,75.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000
50%,NaN,14.000000,4.300000,9.670000e+02,12.000000,1.000000e+05,0.000000,0.000000,NaN,66.000000,...,2018.000000,84.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000
75%,NaN,25.000000,4.500000,2.940100e+04,28.000000,1.000000e+06,0.000000,0.000000,NaN,95.000000,...,2018.000000,86.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000
max,NaN,32.000000,5.000000,7.815831e+07,100.000000,1.000000e+09,1.000000,400.000000,NaN,117.000000,...,2018.000000,87.000000,NaN,NaN,NaN,NaN,NaN,NaN,240.000000,312.000000

In [ ]:
#Finding the maximum number of rows in the dataset

print(pd.options.display.max_rows)

60

In [ ]:
modeis = df.Size.mode()

In [ ]:
print(modeis)

0    11.0
Name: Size, dtype: float64

In [ ]:
#Replacing false values with the mode

df.Size.fillna(modeis,inplace = False)

0       19.0
1       14.0
2        8.7
3       25.0
4        2.8
        ...
9654    53.0
9655     3.6
9656     9.5
9657     NaN
9658    19.0
Name: Size, Length: 9659, dtype: float64

In [ ]:
# Generate count statistics of duplicate entries

if (len(df[df.duplicated()]) > 0):
    print('No. of duplicated entries: ', len(df[df.duplicated()]))
    print(df[df.duplicated(keep = False)].sort_values(by = list(df.columns)).head())
else:
    print('No duplicated entries found.')

No duplicated entries found.

In [ ]:
#Finding the duplicate values in the dataset

In [ ]:
#Unique values of all features

df.nunique().to_frame(name ='Unique Values')

                                         Unique Values
App                                               9659
Category                                            33
Rating                                              39
Reviews                                           5330
Size                                               459
Installs                                            20
Type                                                 3
Price                                               92
Content Rating                                       6
Genres                                             118
Last Updated                                      1377
Current Ver                                       2818
Android Ver                                         34
Last Updated (Year)                                  9
Last Updated (Year/Month)                           88
Category (categorical)                              33
Type (categorical)                                   2
Genres (categorical)                               118
Current Ver (categorical)                         2817
Android Ver (categorical)                           33
Last Updated (Year/Month) (categorical)             88
No_reviews_count                                    95
Reviews_present_count                              131

In [ ]:
#importing seaborn library
import seaborn as sns
#importing matplot library
import matplotlib.pyplot as plt